"""Station names from getAllStationsXML, retrieved 22 September 2026.

https://api.irishrail.ie/realtime/realtime.asmx/getAllStationsXML
No network lookup is needed to display stations without readings.
"""

STATION_NAMES = {
    "ADMTN": "Adamstown",
    "ARHAN": "Ardrahan",
    "ARKLW": "Arklow",
    "ASHTN": "Ashtown",
    "ATHRY": "Athenry",
    "ATHY": "Athy",
    "ATLNE": "Athlone",
    "ATMON": "Attymon",
    "BALNA": "Ballina",
    "BBRDG": "Broombridge",
    "BBRGN": "Balbriggan",
    "BBRHY": "Ballybrophy",
    "BCLAN": "Ballycullane",
    "BFSTC": "Belfast",
    "BHILL": "Birdhill",
    "BMOTE": "Ballymote",
    "BOYLE": "Boyle",
    "BRAY": "Bray",
    "BRGTN": "Bridgetown",
    "BROCK": "Blackrock",
    "BSLOE": "Ballinasloe",
    "BTEER": "Banteer",
    "BTSTN": "Booterstown",
    "BYHNS": "Ballyhaunis",
    "BYSDE": "Bayside",
    "CAHIR": "Cahir",
    "CCONL": "Castleconnell",
    "CENTJ": "CENTRAL JUNCTION",
    "CGLOE": "Carrigaloe",
    "CGTWL": "Carrigtwohill",
    "CHORC": "Park West and Cherry Orchard",
    "CITYJ": "CITY JUNCTION",
    "CJRDN": "Cloughjordan",
    "CKOSH": "Carrick on Shannon",
    "CKOSR": "Carrick on Suir",
    "CLARA": "Clara",
    "CLBAR": "Castlebar",
    "CLDKN": "Clondalkin",
    "CLMEL": "Clonmel",
    "CLMRS": "Claremorris",
    "CLSLA": "Clonsilla",
    "CMINE": "Coolmine",
    "CNLLY": "Dublin Connolly",
    "CNOCK": "Castleknock",
    "COBH": "Cobh",
    "COLNY": "Collooney",
    "CORK": "Cork",
    "CPILE": "Campile",
    "CRGHW": "Craughwell",
    "CRLOW": "Carlow",
    "CSREA": "Castlerea",
    "CTARF": "Clontarf Road",
    "CURAH": "Curragh",
    "CVILL": "Charleville",
    "DBATE": "Donabate",
    "DBYNE": "Dunboyne",
    "DCDRA": "Drumcondra",
    "DCKLS": "Docklands",
    "DDALK": "Dundalk",
    "DGHDA": "Drogheda",
    "DLERY": "Dun Laoghaire",
    "DLKEY": "Dalkey",
    "DRMOD": "Dromod",
    "DUNMR": "DUNMURRAY",
    "ECRTY": "Enniscorthy",
    "ENFLD": "Enfield",
    "ENNIS": "Ennis",
    "ETOWN": "Edgeworthstown",
    "FFORE": "Farranfore",
    "FOTA": "Fota",
    "FXFRD": "Foxford",
    "GALWY": "Galway",
    "GCDK": "Grand Canal Dock",
    "GHANE": "Glounthaune",
    "GLGRY": "Glenageary",
    "GOREY": "Gorey",
    "GORT": "Gort",
    "GRGRD": "Clongriffin",
    "GSTNS": "Greystones",
    "GSTON": "Gormanston",
    "HAFLD": "Hansfield",
    "HOWTH": "Howth",
    "HSTON": "Dublin Heuston",
    "HTOWN": "Harmonstown",
    "HWTHJ": "Howth Junction",
    "HZLCH": "Hazelhatch and Celbridge",
    "KBRCK": "Kilbarrack",
    "KCOCK": "Kilcock",
    "KCOOL": "Kilcoole",
    "KDARE": "Kildare",
    "KILNY": "Killiney",
    "KISHO": "Kishoge",
    "KKNNY": "Kilkenny",
    "KLRNY": "Killarney",
    "KLSTR": "Killester",
    "LBURN": "Lisburn",
    "LDWNE": "Lansdowne Road",
    "LFORD": "Longford",
    "LMRCK": "Limerick",
    "LMRKJ": "Limerick Junction",
    "LSLND": "LittleIsland",
    "LTOWN": "Laytown",
    "LURGN": "Lurgan",
    "LXCON": "Leixlip (Confey)",
    "LXLSA": "Leixlip (Louisa Bridge)",
    "M3WAY": "M3 Parkway",
    "MDLTN": "Midleton",
    "MHIDE": "Malahide",
    "MLGAR": "Mullingar",
    "MLLOW": "Mallow",
    "MLSRT": "Millstreet",
    "MNEBG": "Muine Bheag",
    "MNLAJ": "Manulla Junction",
    "MOIRA": "MOIRA",
    "MONVN": "Monasterevin",
    "MYNTH": "Maynooth",
    "NBRGE": "Newbridge",
    "NEWRY": "Newry",
    "NNAGH": "Nenagh",
    "ORNMR": "Oranmore",
    "PDOWN": "Portadown",
    "PELTN": "Pelletstown",
    "PERSE": "Dublin Pearse",
    "PHNPK": "Navan Road Parkway",
    "PMNCK": "Portmarnock",
    "PTLSE": "Portlaoise",
    "PTRTN": "Portarlington",
    "PWESS": "PARK WEST",
    "RAHNY": "Raheny",
    "RBROK": "Rushbrooke",
    "RCREA": "Roscrea",
    "RDRUM": "Rathdrum",
    "RLEPT": "Rosslare Europort",
    "RLSTD": "Rosslare Strand",
    "RLUSK": "Rush and Lusk",
    "RMORE": "Rathmore",
    "RSCMN": "Roscommon",
    "SALNS": "Sallins",
    "SCOVE": "Sandycove",
    "SEAPT": "Seapoint",
    "SHILL": "Salthill and Monkstown",
    "SIDNY": "Sydney Parade",
    "SKILL": "Shankill",
    "SKRES": "Skerries",
    "SLIGO": "Sligo",
    "SMONT": "Sandymount",
    "SUTTN": "Sutton",
    "SXMBR": "Sixmilebridge",
    "TARA": "Tara Street",
    "THRLS": "Thurles",
    "THTWN": "Thomastown",
    "TIPRY": "Tipperary",
    "TMORE": "Tullamore",
    "TPMOR": "Templemore",
    "TRLEE": "Tralee",
    "WBDGE": "Wellingtonbridge",
    "WBROK": "Woodbrook",
    "WFORD": "Waterford",
    "WLAWN": "Woodlawn",
    "WLOW": "Wicklow",
    "WPORT": "Westport",
    "WXFRD": "Wexford",
}


# Parallel API codes and older stored rows for the same station.
STATION_ALIASES = {
    "ADAMF": "ADMTN", "ADAMS": "ADMTN",
    "CLONF": "CLDKN", "CLONS": "CLDKN",
    "HAZEF": "HZLCH", "HAZES": "HZLCH",
    "KISHF": "KISHO", "KISHS": "KISHO",
    "PWESF": "CHORC",
}


def canonical_station(code):
    code = code.strip().upper()
    return STATION_ALIASES.get(code, code)


def station_codes(codes):
    """One entry per station name, even when configuration repeats API aliases."""
    by_name = {}
    for code in sorted({canonical_station(code) for code in codes if code.strip()}):
        by_name.setdefault(STATION_NAMES.get(code, code).casefold(), code)
    return tuple(by_name[name] for name in sorted(by_name))


PLACE_NAMES = {name.casefold(): name for name in STATION_NAMES.values()}
PLACE_NAMES.update({
    "connolly": STATION_NAMES["CNLLY"],
    "pearse": STATION_NAMES["PERSE"],
    "heuston": STATION_NAMES["HSTON"],
    "hazelhatch": STATION_NAMES["HZLCH"],
})
